server:
  port: 8080
  servlet:
    context-path: /member
spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://c88-mysql:3306/c88?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Y7HJv8Pdd86RtQ92hbPbbhET
  redis:
    host: c88-redis
    port: 6379
    password: 4c55365c-009b-477b-ae47-07f15947c164
    database: 0
  rabbitmq:
    host: c88-rabbitmq
    port: 5672
    username: default_user_HsMJ5kUM_Xl0xkwKC9x
    password: mhXn1tDjBk7WIbzW8IGbf8vABeWWGoDM
#    username: default_user_-sfMfhOP_-GyXw-2jFe
#    password: XoieAxsqH1G2aJP8vr7lW6G4HOD-QHSl
  kafka:
    listener:
      ack-mode: MANUAL
    bootstrap-servers: 10.250.222.1:9092,10.250.222.2:9092,10.250.222.3:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

redisson:
  address: redis://c88-redis:6379
  password: 4c55365c-009b-477b-ae47-07f15947c164

logging:
  level:
    org:
      springframework:
        security: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#hystrix
feign:
  circuitbreaker:
    enabled: true

#中心任務啟用狀態
center-task-client:
  enable: true

#中心任務設定
xxl:
  job:
    executor:
      ip:
      log-retention-days: 30
      app-name: member
      log-path: ./logs/
      address:
      port: 9998
    accessToken:
    admin:
      addresses: http://xxl-job-admin:8088/xxl-job-admin
