server:
  port: 8080
  servlet:
    context-path: /member
spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://c88-mysql:3306/c88?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: c88
    password: su1.%e3:}S2]Gkh,
  redis:
    host: c88-redis
    port: 6379
    password: 956c449b-bd1a-4bfc-8b90-40424b48cef7
    database: 0
  rabbitmq:
    host: c88-rabbitmq
    port: 5672
    username: default_user_Ol0B5e1lRWjOX3kuehT
    password: GK63WRIeFnym9d9dFAcXQ7MW-x1PisvR
  kafka:
    listener:
      ack-mode: MANUAL
    bootstrap-servers: 10.248.222.1:9092,10.248.222.2:9092,10.248.222.3:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

redisson:
  address: redis://c88-redis:6379
  password: 956c449b-bd1a-4bfc-8b90-40424b48cef7

logging:
  level:
    org:
      springframework:
        security: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#hystrix
feign:
  circuitbreaker:
    enabled: true

#中心任務啟用狀態
center-task-client:
  enable: true

#中心任務設定
xxl:
  job:
    executor:
      ip:
      log-retention-days: 30
      app-name: member
      log-path: ./logs/
      address:
      port: 9998
    accessToken:
    admin:
      addresses: http://xxl-job-admin:8088/xxl-job-admin
